name: 百度签到

on:
    workflow_dispatch:
    schedule:
        - cron: "30 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【多多爱运动】"
              run: |
                  node ddayd.js
              env:
                  DDAYD_ddaydCK: ${{ secrets.DDAYD_ddaydCK }}
